import { defineI18nUI } from "fumadocs-ui/i18n";
import { i18n } from "./i18n";

export const { provider } = defineI18nUI(i18n, {
  en: { displayName: "English" },
  ko: {
    displayName: "한국어",
    "Search(search dialog)": "검색",
    "Search(search trigger)": "검색",
    "No results found(search dialog)": "검색 결과가 없습니다",
    "Open Search(search trigger)(aria-label)": "검색 열기",
    "Close Search(search dialog)(aria-label)": "검색 닫기",
    "On this page(table of contents)": "이 페이지의 목차",
    "Table of Contents(inline table of contents)": "목차",
    "No Headings(table of contents)": "제목 없음",
    "Next Page(pagination)": "다음 페이지",
    "Previous Page(pagination)": "이전 페이지",
    "Edit on GitHub(edit page)": "GitHub에서 수정",
    "Back to Home(404 page)": "홈으로 돌아가기",
    "Page Not Found(404 page)": "페이지를 찾을 수 없습니다",
    "The page you are looking for might have been removed, had its name changed, or is temporarily unavailable.(404 page)":
      "찾으시는 페이지가 삭제되었거나, 이름이 변경되었거나, 일시적으로 이용할 수 없는 상태일 수 있습니다.",
    "Choose a language(language switcher)": "언어 선택",
    "Choose a language(language switcher)(aria-label)": "언어 선택",
    "Copy Text(code block)(aria-label)": "복사",
    "Copied Text(code block)(aria-label)": "복사됨",
    "Copy Anchor Link(heading anchor)(aria-label)": "앵커 링크 복사",
    "Copy Markdown(page actions)": "마크다운 복사",
    "View as Markdown(page actions)": "마크다운으로 보기",
    "Open(page actions)": "열기",
    "Light(theme switcher)(aria-label)": "라이트",
    "Dark(theme switcher)(aria-label)": "다크",
    "System(theme switcher)(aria-label)": "시스템",
    "Toggle Theme(theme switcher)(aria-label)": "테마 전환",
    "Open Sidebar(sidebar)(aria-label)": "사이드바 열기",
    "Close Sidebar(sidebar)(aria-label)": "사이드바 닫기",
    "Collapse Sidebar(sidebar)(aria-label)": "사이드바 접기",
    "Show Sidebar(sidebar)": "사이드바 표시",
    "Hide Sidebar(sidebar)": "사이드바 숨기기",
    "Toggle Menu(mobile menu)(aria-label)": "메뉴 열기",
  },
  fr: {
    displayName: "Français",
    "Search(search dialog)": "Rechercher",
    "Search(search trigger)": "Rechercher",
    "No results found(search dialog)": "Aucun résultat",
    "Open Search(search trigger)(aria-label)": "Ouvrir la recherche",
    "Close Search(search dialog)(aria-label)": "Fermer la recherche",
    "On this page(table of contents)": "Sur cette page",
    "Table of Contents(inline table of contents)": "Sommaire",
    "No Headings(table of contents)": "Aucun titre",
    "Next Page(pagination)": "Page suivante",
    "Previous Page(pagination)": "Page précédente",
    // No "Last updated on" entry: driving it needs `lastModifiedTime: "git"`,
    // which reads `git log` per file. CI checkouts (and the Docker build, which
    // excludes `.git`) are shallow, so every page would claim the same date —
    // a wrong date is worse than no date. Add the key back if we ever build
    // from a full clone.
    "Edit on GitHub(edit page)": "Modifier sur GitHub",
    "Back to Home(404 page)": "Retour à l'accueil",
    "Page Not Found(404 page)": "Page introuvable",
    "The page you are looking for might have been removed, had its name changed, or is temporarily unavailable.(404 page)":
      "La page que vous cherchez a peut-être été supprimée, renommée ou est temporairement indisponible.",
    "Choose a language(language switcher)": "Choisir une langue",
    "Choose a language(language switcher)(aria-label)": "Choisir une langue",
    "Copy Text(code block)(aria-label)": "Copier",
    "Copied Text(code block)(aria-label)": "Copié",
    "Copy Anchor Link(heading anchor)(aria-label)": "Copier le lien d'ancre",
    "Copy Markdown(page actions)": "Copier le Markdown",
    "View as Markdown(page actions)": "Voir en Markdown",
    "Open(page actions)": "Ouvrir",
    "Light(theme switcher)(aria-label)": "Clair",
    "Dark(theme switcher)(aria-label)": "Sombre",
    "System(theme switcher)(aria-label)": "Système",
    "Toggle Theme(theme switcher)(aria-label)": "Changer de thème",
    "Open Sidebar(sidebar)(aria-label)": "Ouvrir la barre latérale",
    "Close Sidebar(sidebar)(aria-label)": "Fermer la barre latérale",
    "Collapse Sidebar(sidebar)(aria-label)": "Replier la barre latérale",
    "Show Sidebar(sidebar)": "Afficher la barre latérale",
    "Hide Sidebar(sidebar)": "Masquer la barre latérale",
    "Toggle Menu(mobile menu)(aria-label)": "Ouvrir le menu",
  },
});
